# Defaults
server.port: 8080

spring.datasource:
  url: ${DATABASE_URL:jdbc:h2:mem:testdb}
  driverClassName: org.h2.Driver
  username: sa
  password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring.flyway.locations: classpath:db/migration